### ISSUE TITLE
error transcribing audio

### ISSUE THREAD

**Issue by samedovzaur** [Ai-Austin/BardVoice#3]
![Screenshot 2023-05-19 at 23 11 30](https://github.com/Ai-Austin/BardVoice/assets/101812544/8727e413-3eb2-4a2e-bd5c-2cbbdf6bbb05)

I've named the mp3 file but it didn't even detect or write the sound i dont'n know how to fix it?
PLeasseeee heeeeelllpppp

**Comment by Ai-Austin** [comment]
Your code is written wrong. I responded to your youtube comment with more details.
