### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by CharafChnioune** [Ai-Austin/BardVoice#4]
I get no sound back it creates the audio file for wake detected and that's it I am on a Mac m2 running it on conda 3.10 env

Say "google" to wake me up. 

/Users/user/miniforge3/envs/bard/lib/python3.10/site-packages/whisper/transcribe.py:114: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
No wake word found. Try again.

Say "google" to wake me up.

**Comment by Ai-Austin** [comment]
Could be speaking too soon before program is listening. Has to be an error on your end and not the code. Not an existent issue for me or many other people running the code. Try giving it 1-2 seconds after it requests the wake word to speak. Make sure you don't have a bunch of background noise. Check default mic settings in mac system settings.
