### ISSUE TITLE
helloo weird error on rasbery 

### ISSUE THREAD

**Issue by Valdes11** [Ai-Austin/BardVoice#5]
hello genius error : amirhosain@raspberrypi:~/BardVoice $ python main.py
/home/amirhosain/.local/lib/python3.9/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
def backtrace(trace: np.ndarray):
Traceback (most recent call last):
File "/home/amirhosain/BardVoice/main.py", line 13, in
chatbot = Chatbot(token, ts_token)
TypeError: init() takes 2 positional arguments but 3 were given

**Comment by Valdes11** [comment]
after i removed ts_token error changed to : amirhosain@raspberrypi:~/BardVoice $ python main.py
/home/amirhosain/.local/lib/python3.9/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Traceback (most recent call last):
  File "/home/amirhosain/BardVoice/main.py", line 13, in <module>
    chatbot = Chatbot(token)
  File "/home/amirhosain/.local/lib/python3.9/site-packages/Bard.py", line 85, in __init__
    self.SNlM0e = self.__get_snlm0e()
  File "/home/amirhosain/.local/lib/python3.9/site-packages/Bard.py", line 92, in __get_snlm0e
    SNlM0e = re.search(r"SNlM0e\":\"(.*?)\"", resp.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by iitdwtf** [comment]
> hello genius error : amirhosain@raspberrypi:~/BardVoice $ python main.py /home/amirhosain/.local/lib/python3.9/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details. def backtrace(trace: np.ndarray): Traceback (most recent call last): File "/home/amirhosain/BardVoice/main.py", line 13, in chatbot = Chatbot(token, ts_token) TypeError: init() takes 2 positional arguments but 3 were given

Yes I am getting the same error

**Comment by PhanTrongGiap** [comment]
same error

**Comment by mavacpjm** [comment]
same here

**Comment by Ai-Austin** [comment]
You are using a newer version of the Bard library that has different requirements in your code. If you wish to use the newer version of the library refer to their GitHub repo at https://github.com/acheong08/Bard
